server:
  port: 8080
  servlet:
    context-path: /converter

spring:
  application:
    name: playlist-converter

playlist-converter:
  spotify:
    client-id: ${spotify.clientid}
    client-secret: ${spotify.clientsecret}
